# This file may be used to create a conda environment using:
# $ conda env create -f conda_env.yml

name: mbdeconv
channels:
  - pytorch
  - conda-forge
dependencies:
  - matplotlib=3.6.1
  - numpy=1.24.3
  - python=3.10.6
  - pyyaml=6.0
  - scikit-image=0.19.2
  - scipy=1.10.0
  - seaborn=0.11.2
  - jupyter